package cpen221.mp3.event;

public class ActuatorEvent implements Event {
    //Abstraction Function;
    //The ActuatorEvent class represents an event generated by a actuator. It implements the
    // Event Interface to give methods that could check the timestamp, client ID, entity
    // ID, entity type, and the boolean value.

    //Representation Invariant:
    //TimeStamp should be a non-negative double.
    //ClientId should be a valid and non-negative client ID
    //EntityId should be a valid and non-negative entity ID
    //EntityType is non-null string
    //Value should be true or false

    private double TimeStamp;
    private int ClientId;
    private int EntityId;
    private String EntityType;
    private boolean Value;
    // you can add private fields and methods to this class

    public ActuatorEvent(double TimeStamp, 
                        int ClientId,
                        int EntityId, 
                        String EntityType, 
                        boolean Value) {
        this.TimeStamp = TimeStamp;
        this.ClientId = ClientId;   // remains unregistered
        this.EntityId = EntityId;
        this.EntityType = EntityType;
        this.Value = Value;
    }

    public double getTimeStamp() {
        return TimeStamp;
    }

    public int getClientId() {
        return ClientId;
    }

    public int getEntityId() {
        return EntityId;
    }

    public String getEntityType() {
        return EntityType;
    }

    public boolean getValueBoolean() {
        return Value;
    }

    // Actuator events do not have a double value
    // no need to implement this method
    public double getValueDouble() {
        return -1;
    }

    @Override
    public String toString() {
        return "ActuatorEvent{" +
                "TimeStamp=" + getTimeStamp() +
                ",ClientId=" + getClientId() +
                ",EntityId=" + getEntityId() +
                ",EntityType=" + getEntityType() +
                ",Value=" + getValueBoolean() +
                '}';
    }
}
