package cpen221.mp3.event;

public class SensorEvent implements Event {
    //Abstraction Function;
    //The SensorEvent class represents an event generated by a sensor. It implements the
    // Event Interface to give methods that could check the timestamp, client ID, entity
    // ID, entity type, and the value with the sensor event.

    //Representation Invariant:
    //TimeStamp should be a non-negative double.
    //ClientId should be a valid and non-negative client ID
    //EntityId should be a valid and non-negative entity ID
    //EntityType is non-null string
    //Value should be valid double

    // you can add private fields and methods to this class
    private double TimeStamp;
    private int ClientId;
    private int EntityId;
    private String EntityType;
    private double Value;

    public SensorEvent(double TimeStamp,
                        int ClientId,
                        int EntityId, 
                        String EntityType, 
                        double Value) {
        this.TimeStamp = TimeStamp;
        this.ClientId = ClientId;   // remains unregistered
        this.EntityId = EntityId;
        this.EntityType = EntityType;
        this.Value = Value;
    }

    public double getTimeStamp() {
        return TimeStamp;
    }

    public int getClientId() {
        return ClientId;
    }

    public int getEntityId() {
        return EntityId;
    }

    public String getEntityType() {
        return EntityType;
    }

    public double getValueDouble() {
        return Value;
    }

    // Sensor events do not have a boolean value
    // no need to implement this method
    public boolean getValueBoolean() {
        return false;
    }

    @Override
    public String toString() {
        return "SensorEvent{" +
               "TimeStamp=" + getTimeStamp() +
               ",ClientId=" + getClientId() + 
               ",EntityId=" + getEntityId() +
               ",EntityType=" + getEntityType() + 
               ",Value=" + getValueDouble() + 
               '}';
    }
}
